"""Trace existing festival artwork into compact, normalized particle coordinates.

No source images are changed. The homepage loads the point data instead of two
large PNGs. Re-run after replacing either festival sprite.
"""
import json
import math
from pathlib import Path
from PIL import Image, ImageFilter

ROOT = Path(__file__).resolve().parent.parent


def trace(source, fairy=False):
    alpha = source.getchannel('A').point(lambda a: 255 if a > 120 else 0)
    source = source.crop(alpha.getbbox())
    height = 300
    source = source.resize((round(source.width * height / source.height), height), Image.Resampling.LANCZOS)
    w, h = source.size
    rgba = source.load()
    light = source.convert('L').filter(ImageFilter.GaussianBlur(.7)).load()
    outline, detail = [], []
    for y in range(2, h - 2):
        for x in range(2, w - 2):
            r, g, b, a = rgba[x, y]
            if a < 120:
                continue
            edge = any(rgba[x + dx, y + dy][3] < 120 for dx, dy in [(2, 0), (-2, 0), (0, 2), (0, -2)])
            tone = (2 if g > r * .94 and b > r * .67 else 3 if r > g * 1.24 else 1) if fairy else 0
            if edge:
                outline.append((1000, x, y, tone, 1))
            else:
                gradient = math.hypot(light[x + 1, y] - light[x - 1, y], light[x, y + 1] - light[x, y - 1])
                if gradient > 25 and light[x, y] < 195:
                    detail.append((gradient, x, y, tone, 0))
    # Evenly spaced contour sparks, then the strongest internal folds and ribs.
    cells, points = {}, []
    for _, x, y, tone, edge in outline + sorted(detail, reverse=True):
        spacing = 2.4 if edge else 3.4
        cell = (int(x / 4), int(y / 4))
        nearby = [p for dx in (-1, 0, 1) for dy in (-1, 0, 1) for p in cells.get((cell[0] + dx, cell[1] + dy), [])]
        if any((x - px) ** 2 + (y - py) ** 2 < spacing ** 2 for px, py in nearby):
            continue
        cells.setdefault(cell, []).append((x, y))
        points.append([round((x - w / 2) / h * 1000), round((y - h / 2) / h * 1000), tone, edge])
        if len(points) == 1700:
            break
    return points


rabbit = Image.open(ROOT / 'assets/midautumn/rabbit-lantern-v1.png').convert('RGBA')
# Keep the rabbit's feet, but omit the wooden display plinth below them.
rabbit = rabbit.crop((0, 0, rabbit.width, round(rabbit.height * .878)))
dancers = Image.open(ROOT / 'assets/midautumn/festival-dancers-v1.png').convert('RGBA')
cell = dancers.width // 3
data = {'rabbit': trace(rabbit), 'fairies': [trace(dancers.crop((i * cell, 0, (i + 1) * cell, dancers.height)), True) for i in range(3)]}
target = ROOT / 'atlas-firework-shapes.js'
target.write_text('// Generated by scripts/build-firework-shapes.py from the existing festival artwork.\n'
                  + 'globalThis.QingmingFireworkShapes=' + json.dumps(data, separators=(',', ':')) + ';\n')
print('Wrote', target.name, 'rabbit:', len(data['rabbit']), 'fairies:', [len(p) for p in data['fairies']])
