"""Build a red-and-gold lantern as normalized firework particle coordinates."""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
points = []


def line(x1, y1, x2, y2, tone=0):
    steps = max(1, math.ceil(math.hypot(x2-x1, y2-y1)/8))
    for i in range(steps+1):
        t = i/steps
        points.append([round(x1+(x2-x1)*t), round(y1+(y2-y1)*t), tone, 1])


# Broad red globe with gold ribs, a hanging loop and decorative cap bands.
for i in range(240):
    a = math.tau*i/240
    points.append([round(350*math.cos(a)), round(-70+290*math.sin(a)), 6, 1])
for rib in [-.78, -.42, 0, .42, .78]:
    for i in range(75):
        a = math.pi*i/74
        points.append([round(350*rib*math.sin(a)), round(-70-290*math.cos(a)), 0, 1])
for top, bottom in [(-375, -335), (195, 235)]:
    for y in [top, (top+bottom)/2, bottom]:
        line(-125, y, 125, y)
    line(-125, top, -125, bottom)
    line(125, top, 125, bottom)
line(0, -470, 0, -375)
line(0, 235, 0, 300)
# Gold knot and long red tassel with gold tips.
for a, b in [((0, 265), (28, 295)), ((28, 295), (0, 325)), ((0, 325), (-28, 295)), ((-28, 295), (0, 265))]:
    line(*a, *b)
for x in range(-40, 41, 10):
    line(x*.45, 325, x, 470-abs(x)*.3, 6)
    line(x, 452-abs(x)*.3, x, 480-abs(x)*.3)
data = {'lantern': list(dict.fromkeys(tuple(p) for p in points))}
target = ROOT / 'atlas-firework-shapes.js'
target.write_text('// Generated by scripts/build-firework-shapes.py.\n'
                  + 'globalThis.QingmingFireworkShapes=' + json.dumps(data, separators=(',', ':')) + ';\n')
print('Wrote', target.name, 'lantern:', len(data['lantern']))
