import {categories,createTargets,personBounds,occlusionPolygons,inPolygon,sanitizeCollection,recordFound,collectionStats} from './collection-data.js';
const KEY='ancient-city-collection-v31';
const make=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text)e.textContent=text;return e;};
const button=(text,fn,cls='')=>{const b=make('button',cls,text);b.type='button';b.onclick=()=>fn();return b;};
const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
export function initCollection(api){
 const {people,W,H}=api,targets=createTargets(people,W,H),byId=new Map(targets.map(t=>[t.targetId,t])),byPerson=new Map();
 targets.forEach(t=>t.sceneEntityIds.forEach(id=>byPerson.set(id,t)));
 let state,storage=true;try{state=sanitizeCollection(JSON.parse(localStorage.getItem(KEY)||'null'),targets);}catch{state=sanitizeCollection(null,targets);storage=false;}
 let phase='explore',active=null,restoreFocus=null,completionPending=false,animation=null,hintView=null,hintTimer,noticeTimer,atlasFilter='all',atlasCategory='all',atlasMode='targets';
 const images=new Map(),pixels=new Map();
 const notice=make('div','collection-notice');notice.setAttribute('role','status');notice.setAttribute('aria-live','polite');document.body.append(notice);
 function toast(text){notice.textContent=text;notice.classList.add('visible');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>notice.classList.remove('visible'),4200);}
 function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storage=true;}catch{storage=false;toast('本地存储不可用，本次收集仍保留在当前页面。');}}
 function load(url){if(!images.has(url))images.set(url,new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>{images.delete(url);reject(new Error(url));};im.src=url;}));return images.get(url);}
 function alphaFor(url,im){if(!pixels.has(url)){const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(im,0,0);pixels.set(url,{data:ctx.getImageData(0,0,c.width,c.height).data,w:c.width,h:c.height});}return pixels.get(url);}
 // Low atlas alpha is used for hit testing, the same silhouette as each visible resident.
 for(const p of people){const url=p.assetVariants.low;if(!images.has(url))load(url).then(im=>alphaFor(url,im)).catch(()=>toast('部分人物轮廓加载失败，请刷新重试。'));}
 function thumbnail(t){const box=make('span','collection-thumbnail');box.setAttribute('aria-hidden','true');const b=t.focusBounds;const factor=Math.min(88/b.w,82/b.h);for(const p of t.members){const r=personBounds(p,W,H),sprite=make('span','collection-sprite');sprite.style.cssText=`width:${r.w*factor}px;height:${r.h*factor}px;left:${(r.x-b.x)*factor+(96-b.w*factor)/2}px;top:${(r.y-b.y)*factor+(92-b.h*factor)/2}px;background-image:url("${p.assetVariants.low}");background-size:${(p.atlasColumns||4)*100}% ${(p.atlasRows||2)*100}%;background-position:${p.sprite%(p.atlasColumns||4)*100/((p.atlasColumns||4)-1)}% ${Math.floor(p.sprite/(p.atlasColumns||4))*100/((p.atlasRows||2)-1)}%;`;box.append(sprite);}return box;}
 function selected(){return byId.get(state.selectedTargetId)||targets[0];}
 function preload(t){for(const p of t.members)load(p.assetVariants.high).catch(()=>{});}
 const card=make('aside','collection-clue');card.setAttribute('aria-label','当前寻找目标');card.hidden=true;
 const progress=button('',()=>openAtlas('collection'),'collection-progress');progress.setAttribute('aria-label','我的收集');progress.hidden=true;
 const atlas=make('dialog','collection-atlas');atlas.setAttribute('aria-labelledby','collectionAtlasTitle');
 const focus=make('dialog','collection-focus');focus.setAttribute('aria-labelledby','collectionFocusTitle');
 const summary=make('dialog','collection-summary');summary.setAttribute('aria-label','探索手帖');
 document.body.append(card,progress,atlas,focus,summary);
 let summaryBackdropStart=null;
 const outsideSummary=e=>{const r=summary.getBoundingClientRect();return e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom;};
 summary.addEventListener('pointerdown',e=>{summaryBackdropStart=e.target===summary&&outsideSummary(e)?[e.clientX,e.clientY]:null;});
 summary.addEventListener('pointerup',e=>{if(summaryBackdropStart&&e.target===summary&&outsideSummary(e)&&Math.hypot(e.clientX-summaryBackdropStart[0],e.clientY-summaryBackdropStart[1])<7)summary.close();summaryBackdropStart=null;});
 summary.addEventListener('pointercancel',()=>summaryBackdropStart=null);

 const returnHint=button('返回刚才位置',()=>{if(hintView)api.restore(hintView);clearHint();},'collection-return');returnHint.hidden=true;document.body.append(returnHint);
 let hintGlow;
 function clearHint(){clearTimeout(hintTimer);hintGlow?.remove();hintGlow=null;returnHint.hidden=true;hintView=null;if(phase==='hint')phase='explore';}
 function render(){const t=selected(),h=state.hintUsageByTarget[t.targetId],found=state.foundTargetIds.includes(t.targetId);card.replaceChildren();
 const top=make('div','clue-heading');top.append(make('span','',found?'已收入图鉴':'寻一刻生活'),button('全部目标 ↗',()=>openAtlas('targets')));card.append(top);
 const body=make('div','clue-body'),copy=make('div');copy.append(make('small','',`${categories.find(c=>c[0]===t.categoryId)[1]} · ${t.targetType}`),make('h2','',t.title),make('p','',h?.level?t.hintText:t.clue));body.append(thumbnail(t),copy);card.append(body);
 const actions=make('div','clue-actions');actions.append(button('←',()=>cycle(-1),'clue-prev'),button(found?'再看细节':h?.level?'看看大致范围':'给我提示',()=>found?show(t,false):hint(t),'collection-primary'),button('→',()=>cycle(1),'clue-next'));actions.firstChild.setAttribute('aria-label','上一个目标');actions.lastChild.setAttribute('aria-label','下一个目标');card.append(actions);
 progress.replaceChildren(make('span','','我的收集'),make('strong','',`${state.foundTargetIds.length} / ${targets.length}`));progress.setAttribute('aria-label',`我的收集，已找到 ${state.foundTargetIds.length} 个，共 ${targets.length} 个`);
 }
 function choose(t){state.selectedTargetId=t.targetId;save();render();preload(t);}
 function cycle(direction){choose(targets[(targets.indexOf(selected())+direction+targets.length)%targets.length]);}
 let swipe;
 card.addEventListener('pointerdown',e=>{if(!e.target.closest('button'))swipe=[e.clientX,e.clientY];});card.addEventListener('pointerup',e=>{if(swipe&&Math.abs(e.clientX-swipe[0])>55&&Math.abs(e.clientY-swipe[1])<30)cycle(e.clientX<swipe[0]?1:-1);swipe=null;});card.addEventListener('pointercancel',()=>swipe=null);
 function hint(t){const h=state.hintUsageByTarget[t.targetId]??={level:0,count:0,guided:false};h.count++;if(h.level===0){h.level=1;save();render();toast(t.hintText);return;}h.level=2;save();render();if(!hintView)hintView=api.view();hintGlow?.remove();clearTimeout(hintTimer);phase='hint';const b=t.hintBounds;api.move(b.x,b.y,Math.min(api.max(),2.5));hintGlow=make('div','collection-range');hintGlow.style.cssText=`left:${b.x*100}%;top:${b.y*100}%;width:${b.w*100}%;height:${b.h*100}%;`;document.getElementById('world').append(hintGlow);returnHint.hidden=false;hintTimer=setTimeout(()=>{hintGlow?.remove();hintGlow=null;phase='explore';},3500);}
 function openAtlas(mode){api.stop();atlasMode=mode;atlasFilter='all';atlasCategory='all';renderAtlas();atlas.showModal();}
 function renderAtlas(){atlas.replaceChildren();let handleSwiped=false;const handle=button('─',()=>{if(handleSwiped){handleSwiped=false;return;}atlas.classList.toggle('expanded');handle.setAttribute('aria-expanded',atlas.classList.contains('expanded'));},'atlas-handle');handle.setAttribute('aria-label','展开或收起收藏册');handle.setAttribute('aria-expanded',atlas.classList.contains('expanded'));let startY;handle.addEventListener('pointerdown',e=>{startY=e.clientY;handle.setPointerCapture(e.pointerId);});handle.addEventListener('pointerup',e=>{if(Math.abs(e.clientY-startY)>25){handleSwiped=true;atlas.classList.toggle('expanded',e.clientY<startY);handle.setAttribute('aria-expanded',atlas.classList.contains('expanded'));}});atlas.append(handle);const head=make('div','atlas-head'),title=make('h2','',atlasMode==='collection'?'我的收藏册':'这一城，等你发现');title.id='collectionAtlasTitle';head.append(make('small','','人物 · 生活 · 烟火'),title,button('×',()=>atlas.close(),'collection-close'));head.lastChild.setAttribute('aria-label','关闭目标列表');atlas.append(head);
 const stats=collectionStats(state);atlas.append(make('p','atlas-caption',`${stats.found} / ${targets.length} 已收入图鉴 · ${stats.independent} 个独立找到`));
 const filters=make('div','atlas-filters');const select=make('select');select.setAttribute('aria-label','按收集状态筛选');for(const[value,label]of [['all','全部'],['unfound','未找到'],['found','已收集']]){const o=make('option','',label);o.value=value;select.append(o);}select.value=atlasFilter;select.onchange=()=>{atlasFilter=select.value;renderAtlas();atlas.querySelector('select').focus();};filters.append(select);
 const cats=make('select');cats.setAttribute('aria-label','按场景分类筛选');for(const[value,label]of [['all','全部场景'],...categories]){const o=make('option','',label);o.value=value;cats.append(o);}cats.value=atlasCategory;cats.onchange=()=>{atlasCategory=cats.value;renderAtlas();atlas.querySelectorAll('select')[1].focus();};filters.append(cats);atlas.append(filters);
 const list=make('div','atlas-list');for(const[id,name]of categories){if(atlasCategory!=='all'&&atlasCategory!==id)continue;const all=targets.filter(t=>t.categoryId===id),items=all.filter(t=>atlasFilter==='all'||(state.foundTargetIds.includes(t.targetId)?atlasFilter==='found':atlasFilter==='unfound'));if(!items.length)continue;const section=make('section'),heading=make('h3','',`${name}　${all.filter(t=>state.foundTargetIds.includes(t.targetId)).length}/${all.length}`),grid=make('div','atlas-grid');section.append(heading,grid);for(const t of items){const found=state.foundTargetIds.includes(t.targetId),b=button('',()=>{atlas.close();if(found)show(t,false);else choose(t);},'atlas-target'+(found?' is-found':'')+(t.targetId===state.selectedTargetId?' is-selected':''));b.dataset.target=t.targetId;b.append(thumbnail(t),make('strong','',t.title),make('small','',found?'✓ 已收集':t.targetId===state.selectedTargetId?'正在寻找':t.targetType+' · 未找到'));b.setAttribute('aria-label',`${t.title}，${found?'已收集，查看细节':'未找到，设为寻找目标'}`);grid.append(b);}list.append(section);}if(!list.childElementCount)list.append(make('p','atlas-empty','这一页还没有人物。去画中找找吧。'));atlas.append(list);
 const footer=make('div','atlas-footer');footer.append(button('导览查看',()=>{atlas.close();guide();}),button('设置',()=>{atlas.close();settings();}),button('回到画卷',()=>atlas.close(),'collection-primary'));atlas.append(footer);}
 function openSummary(title,description,actions){summary.classList.remove('collection-guide');summary.replaceChildren(make('h2','',title),make('p','',description));const row=make('div','summary-actions');for(const[label,fn]of actions)row.append(button(label,fn));summary.append(row);if(!summary.open)summary.showModal();}
 function settings(){openSummary('探索手帖','收集进度保存在这台设备。重新开始只清除收集与提示记录。',[['重新开始',()=>openSummary('重新寻找这一城？','已收集的人物与提示记录将被清除，画卷位置和声音设置保留。',[['保留进度',()=>summary.close()],['确认重新开始',()=>{state=sanitizeCollection(null,targets);save();render();summary.close();toast('新的收藏册已展开。');}]])],['继续探索',()=>summary.close()]]);}
 function preview(t=selected()){if(focus.open||phase==='return')return;const h=state.hintUsageByTarget[t.targetId]??={level:0,count:0,guided:false};if(!state.foundTargetIds.includes(t.targetId))h.guided=true;save();show(t,false,true);}
 function guide(){summary.classList.add('collection-guide');const head=make('div','guide-head'),close=button('×',()=>summary.close(),'collection-close');close.setAttribute('aria-label','关闭人物导览');head.append(make('h2','','人物导览'),close,make('p','','可直接欣赏每个人物。导览不会增加收集数；看过导览的目标之后计为借助提示找到。'));summary.replaceChildren(head);const list=make('div','guide-list');for(const t of targets)list.append(button(t.title,()=>{summary.close();preview(t);}));const footer=make('div','guide-footer');footer.append(button('返回画卷',()=>summary.close(),'collection-primary'));summary.append(list,footer);summary.showModal();}
 function complete(){state.completionSeen=true;save();const stats=collectionStats(state);openSummary('这一城的烟火，被你一一发现。',`共 ${stats.found} 个生活片段 · 独立找到 ${stats.independent} 个 · 借助提示找到 ${stats.helped} 个`,[['查看图鉴',()=>{summary.close();openAtlas('collection');}],['继续逛逛',()=>summary.close()]]);}
 // Focus is a presentation of the same sprite rectangles, at their world-relative spacing.
 let art,stage,stageScale=1,panX=0,panY=0,baseFit=1,nativeLimit=1,artVersion=0,savedView,focusGuided=false,focusPointers=new Map(),focusGesture=null,focusPinch=null;
 async function drawTarget(t,high=true){const loaded=await Promise.all(t.members.map(p=>load(high?p.assetVariants.high:p.assetVariants.low)));const b=t.focusBounds,ratio=Math.min(...t.members.map((p,i)=>(loaded[i].height/(p.atlasRows||2))/p.scale));const c=document.createElement('canvas');c.width=Math.ceil(b.w*ratio);c.height=Math.ceil(b.h*ratio);const ctx=c.getContext('2d');t.members.forEach((p,i)=>{const im=loaded[i],r=personBounds(p,W,H),cols=p.atlasColumns||4,rows=p.atlasRows||2;ctx.drawImage(im,(p.sprite%cols)*im.width/cols,Math.floor(p.sprite/cols)*im.height/rows,im.width/cols,im.height/rows,(r.x-b.x)*ratio,(r.y-b.y)*ratio,r.w*ratio,r.h*ratio);});return c;}
 function geometry(){const b=active.focusBounds,r=stage.getBoundingClientRect();baseFit=Math.min(r.width*.78/b.w,r.height*.85/b.h,nativeLimit);return{left:r.left+r.width/2-b.w*baseFit/2,top:r.top+r.height/2-b.h*baseFit/2,w:b.w*baseFit,h:b.h*baseFit};}
 function layout(){if(!active||!art)return;const g=geometry();stageScale=Math.min(stageScale,Math.max(1,nativeLimit/baseFit));const r=stage.getBoundingClientRect();panX=Math.max(-g.w*(stageScale-1)/2,Math.min(g.w*(stageScale-1)/2,panX));panY=Math.max(-g.h*(stageScale-1)/2,Math.min(g.h*(stageScale-1)/2,panY));art.style.width=g.w+'px';art.style.height=g.h+'px';art.style.left=(r.width-g.w)/2+'px';art.style.top=(r.height-g.h)/2+'px';art.style.transform=`translate(${panX}px,${panY}px) scale(${stageScale})`;}
 function detailZoom(factor){stageScale=Math.max(1,Math.min(nativeLimit/baseFit,stageScale*factor));layout();}
 function travel(reverse=false){animation?.cancel();const g=geometry(),origin=api.project(active.focusBounds),from=`translate(${origin.x-g.left}px,${origin.y-g.top}px) scale(${origin.w/g.w},${origin.h/g.h})`,to='translate(0px,0px) scale(1)';art.style.transformOrigin='0 0';animation=art.animate(reduced()?[{opacity:reverse?1:0},{opacity:reverse?0:1}]:[{transform:reverse?to:from,opacity:1},{transform:reverse?from:to,opacity:1}],{duration:reduced()?120:reverse?400:550,easing:'cubic-bezier(.22,.72,.18,1)',fill:'none'});return animation.finished.catch(()=>{});}
 async function show(t,isNew=false,guided=false){if(focus.open||phase==='return')return;clearHint();notice.classList.remove('visible');document.getElementById('story').hidden=true;api.stop();savedView=api.view();restoreFocus=document.activeElement;active=t;focusGuided=guided;phase='discover';stageScale=1;panX=panY=0;nativeLimit=512/Math.max(...t.members.map(p=>p.scale))/Math.max(1,devicePixelRatio);focus.replaceChildren();
 const top=make('div','focus-top');top.append(make('span','',`${categories.find(c=>c[0]===t.categoryId)[1]} / ${t.targetType}`),button('×',closeFocus,'collection-close'));top.lastChild.setAttribute('aria-label','关闭特写');focus.append(top);stage=make('div','focus-stage');stage.setAttribute('aria-label','人物细节，可拖动或缩放');stage.tabIndex=0;focus.append(stage);
 const copy=make('div','focus-copy'),title=make('h2','',t.title);title.id='collectionFocusTitle';copy.append(make('span',isNew?'focus-stamp':'focus-status',guided?'导览欣赏 · 不计入收集':isNew?'已收入图鉴':'再看一刻生活'),title,make('p','',t.description));const controls=make('div','focus-controls');controls.append(button('−',()=>detailZoom(1/1.25)),button('恢复适配',()=>{stageScale=1;panX=panY=0;layout();}),button('＋',()=>detailZoom(1.25)),button('继续探索',closeFocus,'collection-primary'));controls.firstChild.setAttribute('aria-label','缩小人物');controls.children[2].setAttribute('aria-label','放大人物');copy.append(controls,button('在画中查看',()=>closeFocus(true),'focus-locate'));focus.append(copy);focus.showModal();document.body.classList.add('collection-focusing');installDetailGestures();
 const version=++artVersion;try{art=await drawTarget(t,false);if(version!==artVersion)return;art.className='focus-art';stage.append(art);nativeLimit=art.height/t.focusBounds.h/Math.max(1,devicePixelRatio);layout();await upgrade(t,version);if(version!==artVersion)return;api.hideMembers(t.sceneEntityIds,true);layout();await travel();if(version===artVersion){art.style.transformOrigin='50% 50%';phase='focus';stage.focus();}}catch{if(version===artVersion){phase='focus';stage.append(make('p','focus-error','人物暂未加载成功，收集记录已保留。'),button('重试',()=>{closeFocus();setTimeout(()=>show(t,false,guided),450);}));}}
 }
 async function upgrade(t,version){try{const hd=await drawTarget(t,true);if(version!==artVersion)return;art.width=hd.width;art.height=hd.height;art.getContext('2d').drawImage(hd,0,0);nativeLimit=hd.height/t.focusBounds.h/Math.max(1,devicePixelRatio);layout();}catch{if(version!==artVersion)return;const error=make('div','focus-load-error');error.append(make('span','','高清素材加载失败，暂用预览。'),button('重试高清',async()=>{error.remove();await upgrade(t,version);}));focus.querySelector('.focus-copy').append(error);}}
 async function closeFocus(locate=false){if(!focus.open)return;if(phase==='return'){animation?.finish();return;}const t=active;phase='return';++artVersion;animation?.cancel();stageScale=1;panX=panY=0;if(art?.isConnected){layout();if(!focusGuided&&state.foundTargetIds.includes(t.targetId)&&!reduced()){const token=thumbnail(t);token.classList.add('collection-token');document.body.append(token);const dest=progress.getBoundingClientRect();token.animate([{transform:`translate(${innerWidth/2-48}px,${innerHeight/2-46}px) scale(.7)`,opacity:1},{transform:`translate(${dest.left}px,${dest.top}px) scale(.2)`,opacity:0}],{duration:420,easing:'ease-in'}).finished.finally(()=>token.remove());}await travel(true);}
 api.hideMembers(t.sceneEntityIds,false);focus.close();document.body.classList.remove('collection-focusing');api.restore(savedView);phase='explore';active=null;art=null;focusPointers.clear();focusGesture=focusPinch=null;if(restoreFocus?.isConnected)restoreFocus.focus({preventScroll:true});else api.focus();if(locate){const b=t.hintBounds;api.move(b.x,b.y,Math.min(api.max(),3.8));toast(t.title+'就在这一带，放大后观察人物。');}if(completionPending){completionPending=false;complete();}}
 focus.addEventListener('cancel',e=>{e.preventDefault();closeFocus();});
 function installDetailGestures(){focusPointers.clear();focusGesture=null;focusPinch=null;stage.addEventListener('wheel',e=>{e.preventDefault();if(phase==='focus')detailZoom(Math.exp(-e.deltaY*.0015));},{passive:false});stage.addEventListener('pointerdown',e=>{if(phase!=='focus')return;stage.setPointerCapture(e.pointerId);focusPointers.set(e.pointerId,[e.clientX,e.clientY]);focusGesture={x:e.clientX,y:e.clientY,moved:false,onArt:e.target===art,multi:focusPointers.size>1};if(focusPointers.size===2){const[a,b]=[...focusPointers.values()];focusPinch=Math.hypot(a[0]-b[0],a[1]-b[1]);}});stage.addEventListener('pointermove',e=>{if(!focusPointers.has(e.pointerId))return;const prev=focusPointers.get(e.pointerId);focusPointers.set(e.pointerId,[e.clientX,e.clientY]);if(Math.hypot(e.clientX-focusGesture.x,e.clientY-focusGesture.y)>6)focusGesture.moved=true;if(focusPointers.size===2){const[a,b]=[...focusPointers.values()],d=Math.hypot(a[0]-b[0],a[1]-b[1]);if(focusPinch)detailZoom(d/focusPinch);focusPinch=d;return;}panX+=e.clientX-prev[0];panY+=e.clientY-prev[1];layout();});const end=e=>{if(!focusPointers.has(e.pointerId))return;focusPointers.delete(e.pointerId);if(focusPointers.size)return;if(e.type==='pointerup'&&!focusGesture.moved&&!focusGesture.onArt&&!focusGesture.multi)closeFocus();focusGesture=null;focusPinch=null;};stage.addEventListener('pointerup',end);stage.addEventListener('pointercancel',end);stage.addEventListener('keydown',e=>{if(['+','=','-','Home','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();if(e.key==='Home'){stageScale=1;panX=panY=0;}else if(e.key==='+'||e.key==='=')detailZoom(1.25);else if(e.key==='-')detailZoom(1/1.25);else{panX+=e.key==='ArrowLeft'?25:e.key==='ArrowRight'?-25:0;panY+=e.key==='ArrowUp'?25:e.key==='ArrowDown'?-25:0;}layout();}});}
 function opaque(p,px,py){const r=personBounds(p,W,H);if(px<r.x||py<r.y||px>=r.x+r.w||py>=r.y+r.h)return false;const a=pixels.get(p.assetVariants.low);if(!a)return false;const cols=p.atlasColumns||4,rows=p.atlasRows||2,ax=Math.min(a.w-1,Math.floor((p.sprite%cols+(px-r.x)/r.w)*a.w/cols)),ay=Math.min(a.h-1,Math.floor((Math.floor(p.sprite/cols)+(py-r.y)/r.h)*a.h/rows));return a.data[(ay*a.w+ax)*4+3]>55;}
 function hit(cx,cy){if(phase==='discover'||phase==='focus'||phase==='return'||atlas.open||summary.open)return true;const v=api.view(),px=(cx-v.x)/v.scale,py=(cy-v.y)/v.scale;if(occlusionPolygons.some(poly=>inPolygon(px/W,py/H,poly)))return false;const front=[...people].reverse().find(p=>opaque(p,px,py));let t=front&&byPerson.get(front.id);if(!t){if(!front){const dots=[[0,-4],[0,4],[-4,0],[4,0]];const near=new Set();for(const[dx,dy]of dots){const qx=px+dx/v.scale,qy=py+dy/v.scale;if(occlusionPolygons.some(poly=>inPolygon(qx/W,qy/H,poly)))continue;const p=[...people].reverse().find(p=>opaque(p,qx,qy));if(p&&byPerson.has(p.id))near.add(byPerson.get(p.id));}if(near.size>1){toast('这里的人物挨得很近，再放大一点看看。');return true;}if(near.size===1)t=[...near][0];}if(!t)return false;}
 if(Math.min(...t.members.map(p=>p.scale))*v.scale<18){toast('再放大一些，看看他的衣着与动作。');return true;}
 state.selectedTargetId=t.targetId;const fresh=recordFound(state,t.targetId);if(fresh){save();completionPending=state.foundTargetIds.length===targets.length&&!state.completionSeen;}render();show(t,fresh);return true;}
 window.addEventListener('resize',()=>{if(active){animation?.finish();layout();}});
 document.addEventListener('keydown',e=>{if(e.key==='Enter'&&document.activeElement===document.getElementById('viewport')){e.preventDefault();hit(innerWidth/2,innerHeight/2);}});
 render();preload(selected());card.hidden=false;progress.hidden=false;if(!storage)toast('本地存储不可用，本次收集仍保留在当前页面。');
 return{hit,preview,interrupt(){if(phase==='hint')phase='explore';},busy:()=>focus.open,targets};
}
