import {targets,eggs,VERSION} from './explore-data.js';
import {hitTarget,sanitize} from './explore-geometry.js';
const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg',KEY='ancient-city-explore-v1';
const viewport=$('viewport'),world=$('world'),painting=$('painting'),effects=$('effects');
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const mobile=matchMedia('(max-width:700px)');
let state=sanitize(null,targets,eggs,VERSION),storage=true,saved=false;
try{const raw=JSON.parse(localStorage.getItem(KEY));if(raw){state=sanitize(raw,targets,eggs,VERSION);saved=true}}catch{storage=false}
let started=false,loaded=false,W=2000,H=784,vw=innerWidth,vh=innerHeight,minScale=1,scale=1,tx=0,ty=0,selected=null,hintLevels={},frame=0,lastTick=performance.now(),toastTimer,restoreFocus,completionPending=false;
let audio;const points=new Map();let gesture=null,pinch=null,inertia=0;
const debug=['localhost','127.0.0.1','[::1]'].includes(location.hostname)&&new URLSearchParams(location.search).get('debug')==='1';
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3500)}
function viewState(){return{x:(vw/2-tx)/(W*scale),y:(vh/2-ty)/(H*scale),zoom:scale/minScale}}
function save(){if(!started)return;state.view=viewState();if(storage)try{localStorage.setItem(KEY,JSON.stringify(state));saved=true}catch{storage=false;toast('本次进度仅在当前页面保留')}}
function bounds(){const margin=32;tx=W*scale<=vw?(vw-W*scale)/2:Math.max(vw-W*scale-margin,Math.min(margin,tx));ty=H*scale<=vh?(vh-H*scale)/2:Math.max(vh-H*scale-margin,Math.min(margin,ty))}
function paint(){bounds();world.style.transform=`translate(${tx}px,${ty}px) scale(${scale})`;$('zoomLevel').textContent=(scale/minScale).toFixed(1)+'×';effects.querySelectorAll('.marker').forEach(el=>el.style.display=scale/minScale>=1.65?'':'none')}
function stop(){cancelAnimationFrame(frame);cancelAnimationFrame(inertia)}
function moveTo(x,y,s,animate=true){stop();s=Math.max(minScale,Math.min(minScale*4,s));const from=[tx,ty,scale],to=[vw/2-x*W*s,vh/2-y*H*s,s];if(reduced.matches||!animate){[tx,ty,scale]=to;paint();save();return}const start=performance.now();function step(now){const p=Math.min(1,(now-start)/500),e=1-(1-p)**3;[tx,ty,scale]=from.map((v,i)=>v+(to[i]-v)*e);paint();if(p<1)frame=requestAnimationFrame(step);else save()}frame=requestAnimationFrame(step)}
function zoom(factor,x=vw/2,y=vh/2){stop();const next=Math.max(minScale,Math.min(minScale*4,scale*factor));tx=x-(x-tx)*next/scale;ty=y-(y-ty)*next/scale;scale=next;paint();save()}
function fit(animate=true){moveTo(.5,.5,minScale,animate)}
function resize(){const v=loaded?viewState():null;vw=innerWidth;vh=innerHeight;minScale=Math.min(vw/W,vh/H);if(v){scale=minScale*v.zoom;tx=vw/2-v.x*W*scale;ty=vh/2-v.y*H*scale}else{scale=minScale;tx=(vw-W*scale)/2;ty=(vh-H*scale)/2}paint()}
function svg(name,attrs,parent=effects){const el=document.createElementNS(NS,name);for(const[k,v]of Object.entries(attrs))el.setAttribute(k,v);parent.append(el);return el}
function flash(x,y,type='glow'){const el=svg('ellipse',{cx:x*W,cy:y*H,rx:type==='ripple'?45:24,ry:type==='ripple'?12:24,class:'effect'});setTimeout(()=>el.remove(),1700)}
function markers(){effects.querySelectorAll('.marker').forEach(e=>e.remove());state.found.forEach(id=>{const t=targets.find(t=>t.id===id);svg('circle',{cx:t.focusPoint[0]*W,cy:t.focusPoint[1]*H,r:5,class:'marker'})});paint()}
function render(){ $('progress').textContent=`${state.found.length} / 12`;$('sound').textContent=state.sound?'声音 开':'声音 关';$('sound').setAttribute('aria-pressed',state.sound);$('targetList').replaceChildren();targets.forEach(t=>{const found=state.found.includes(t.id);const b=document.createElement('button');b.className='target'+(selected===t.id?' selected':'');b.setAttribute('aria-label',`${t.name}，${found?'已发现':t.difficulty+'，未发现'}。${t.clue}`);b.setAttribute('aria-pressed',selected===t.id);b.innerHTML=`<img src="${t.thumbnail}" alt="" draggable="false"><span class="copy"><strong>${t.name}</strong><small>${found?'已收集':t.difficulty+' · '+(selected===t.id?'正在寻找':'待寻')}</small></span><span class="check">${found?'✓':'○'}</span>`;b.onclick=()=>{if(found){moveTo(...t.focusPoint,minScale*3);detail(t,false,b)}else{selected=t.id;render();clue(t);if(mobile.matches)collapse(true)}};$('targetList').append(b)});markers();if($('tasks').classList.contains('collapsed'))$('drawerSummary').textContent=selected?targets.find(t=>t.id===selected).name+' · 展开＋':'十二处烟火 · 展开＋'}
function clue(t){$('clue').hidden=false;$('clue').innerHTML=`<button class="dismiss" aria-label="收起线索">×</button><strong>${t.name}</strong><p>${t.clue}</p><button class="hint-button">${hintLevels[t.id]?'提示二 · 看看大致范围':'提示一 · 再给一句线索'}</button>`;$('clue').querySelector('.dismiss').onclick=()=>$('clue').hidden=true;$('clue').querySelector('.hint-button').onclick=()=>hint(t)}
function hint(t){state.hints++;if(!hintLevels[t.id]){hintLevels[t.id]=1;clue(t);$('clue').querySelector('p').textContent=t.hintText}else{const[x,y,w,h]=t.hintRegion;moveTo(x,y,minScale*2.2);const el=svg('ellipse',{cx:x*W,cy:y*H,rx:w*W/2,ry:h*H/2,class:'hint'});setTimeout(()=>el.remove(),3000)}save()}
function openModal(title,eyebrow,content,actions,trigger=document.activeElement){if(!$('modal').open)restoreFocus=trigger;$('modalTitle').textContent=title;$('modalEyebrow').textContent=eyebrow;$('modalContent').innerHTML=content;$('modalActions').replaceChildren();for(const[label,fn,primary]of actions){const b=document.createElement('button');b.textContent=label;if(primary)b.className='primary';b.onclick=fn;$('modalActions').append(b)}if(!$('modal').open)$('modal').showModal()}
function closeModal(){$('modal').close()}
$('closeModal').onclick=closeModal;
$('modal').addEventListener('close',()=>{lastTick=performance.now();if(restoreFocus?.isConnected)restoreFocus.focus();else viewport.focus();if(completionPending){completionPending=false;complete()}});
function detail(t,isNew=false,trigger){openModal(t.name,isNew?'寻得一处 · 烟火入册':'画中故事',`<img class="detail-image" src="${t.thumbnail}" alt="${t.name}局部"><p>${t.description}</p>`,[['继续寻找',closeModal,true]],trigger)}
function tone(kind='discover'){if(!state.sound)return;try{audio??=new AudioContext();audio.resume().catch(()=>{});const now=audio.currentTime;const notes=kind==='sound'?[330,440,392,294]:[523,659];notes.forEach((f,i)=>{const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0,now+i*.1);g.gain.linearRampToValueAtTime(.06,now+i*.1+.025);g.gain.exponentialRampToValueAtTime(.001,now+i*.1+.3);o.connect(g).connect(audio.destination);o.start(now+i*.1);o.stop(now+i*.1+.31)})}catch{toast('声音暂时不可用，仍可继续探索')}}
function discover(x,y){if(debug)toast(`坐标 ${x.toFixed(4)}, ${y.toFixed(4)}`);const t=hitTarget(targets,x,y);const egg=eggs.find(e=>Math.hypot((x-e.point[0])*W,(y-e.point[1])*H)<e.radius*W);if(egg){const first=!state.eggs.includes(egg.id);if(first){state.eggs.push(egg.id);toast(egg.text+(egg.effect==='sound'&&!state.sound?'（开启声音可听见短音）':''))}flash(...egg.point,egg.effect);if(egg.effect==='sound')tone('sound');save()}if(t){const fresh=!state.found.includes(t.id);if(fresh){state.found.push(t.id);flash(...t.focusPoint);tone();if(state.found.length===12)completionPending=true;render();save()}detail(t,fresh,viewport)}else if(!egg)flash(x,y,'ripple')}
function complete(){const mins=Math.floor(state.seconds/60),secs=Math.floor(state.seconds%60);openModal('你已收集这一城的烟火。','十二处寻趣 · 一城生活',`<div class="stats"><div><strong>12 / 12</strong><span>已发现目标</span></div><div><strong>${mins}分${secs}秒</strong><span>有效探索时长</span></div><div><strong>${state.hints}</strong><span>提示使用次数</span></div><div><strong>${state.eggs.length} / 3</strong><span>隐藏彩蛋</span></div></div>`,[['继续逛逛',closeModal,true],['重新探索',confirmReset]])}
function reset(){const sound=state.sound;state=sanitize(null,targets,eggs,VERSION);state.sound=sound;selected=null;hintLevels={};completionPending=false;effects.querySelectorAll('.hint,.effect').forEach(e=>e.remove());$('clue').hidden=true;closeModal();moveTo(.52,.51,minScale*(mobile.matches?3:1.65),false);render();save();toast('新的寻趣手帖已展开')}
function confirmReset(){openModal('重新展开画卷？','重新探索','<p>将清除已发现目标、彩蛋、提示次数与探索时长。</p>',[['保留进度',closeModal],['确认重新探索',reset,true]])}
function guide(){openModal('列表导览','不必寻物，也能读懂画卷','<p class="muted">逐项阅读画中故事。导览阅读不会计入寻物完成进度。</p><div id="guideList"></div>',[['返回画卷',closeModal,true]]);targets.forEach(t=>{const b=document.createElement('button');b.className='guide-row';b.textContent=t.name+' · 阅读故事 →';b.onclick=()=>{openModal(t.name,'列表导览 · 不计入寻物进度',`<img class="detail-image" src="${t.thumbnail}" alt="${t.name}局部"><p>${t.description}</p>`,[['返回导览',guide],['返回画卷',closeModal,true]])};$('guideList').append(b)})}
$('guide').onclick=guide;
$('help').onclick=()=>openModal('怎样在画里寻趣','随心寻找 · 不限顺序','<p>电脑：拖动移动，滚轮缩放，点击寻找。手机：单指移动，双指缩放，轻点寻找。</p><p>键盘：聚焦画卷后用方向键移动，＋ / − 缩放，Home 查看全图。Tab 可依次访问任务、提示和按钮，Escape 关闭弹层。</p><p>先选目标可查看线索；提示分为文字与区域两级。已发现目标可再次阅读。也可以通过列表导览直接阅读全部故事。</p>',[['列表导览',guide],['继续探索',closeModal,true]]);
$('more').onclick=()=>openModal('探索手帖','你的进度保存在这台设备','<p>自在逛逛，离开后还可以接着找。</p>',[['列表导览',guide],...(state.found.length===12?[['查看探索结果',complete]]:[]),['重新探索',confirmReset],['返回画卷',closeModal,true]]);
$('sound').onclick=()=>{state.sound=!state.sound;render();save();if(state.sound)tone()};
function collapse(value){$('tasks').classList.toggle('collapsed',value);$('toggleTasks').setAttribute('aria-expanded',!value);$('drawerSummary').textContent=value?(selected?targets.find(t=>t.id===selected).name+' · 展开＋':'十二处烟火 · 展开＋'):'收起 −'}
$('toggleTasks').onclick=()=>collapse(!$('tasks').classList.contains('collapsed'));collapse(mobile.matches);
$('zoomIn').onclick=()=>zoom(1.3);$('zoomOut').onclick=()=>zoom(1/1.3);$('fit').onclick=()=>fit();
$('onboarding').querySelector('button').onclick=()=>$('onboarding').hidden=true;const practiced=new Set();function practice(type){practiced.add(type);if(practiced.size===3)$('onboarding').hidden=true}
viewport.addEventListener('wheel',e=>{if(!started)return;e.preventDefault();zoom(Math.exp(-e.deltaY*.0015),e.clientX,e.clientY);practice('zoom')},{passive:false});
viewport.addEventListener('pointerdown',e=>{if(!started||e.button>0)return;stop();viewport.focus({preventScroll:true});viewport.setPointerCapture(e.pointerId);points.set(e.pointerId,{x:e.clientX,y:e.clientY});if(points.size===1){gesture={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,lastTime:performance.now(),vx:0,vy:0,moved:false,multi:false}}else{gesture.multi=true;const[a,b]=[...points.values()];pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),x:(a.x+b.x)/2,y:(a.y+b.y)/2}}});
viewport.addEventListener('pointermove',e=>{if(!points.has(e.pointerId))return;points.set(e.pointerId,{x:e.clientX,y:e.clientY});if(points.size>=2){const[a,b]=[...points.values()],x=(a.x+b.x)/2,y=(a.y+b.y)/2,d=Math.hypot(a.x-b.x,a.y-b.y);if(pinch){tx+=x-pinch.x;ty+=y-pinch.y;zoom(d/Math.max(pinch.distance,1),x,y)}pinch={distance:d,x,y};practice('zoom');return}if(!gesture)return;const now=performance.now(),dt=Math.max(8,now-gesture.lastTime),dx=e.clientX-gesture.lastX,dy=e.clientY-gesture.lastY;tx+=dx;ty+=dy;gesture.vx=dx/dt;gesture.vy=dy/dt;gesture.lastX=e.clientX;gesture.lastY=e.clientY;gesture.lastTime=now;if(Math.hypot(e.clientX-gesture.x,e.clientY-gesture.y)>7)gesture.moved=true;paint()});
function endPointer(e){if(!points.has(e.pointerId))return;points.delete(e.pointerId);if(points.size){const p=[...points.values()][0];gesture.lastX=p.x;gesture.lastY=p.y;pinch=null;return}const g=gesture;gesture=null;pinch=null;if(!g)return;if(e.type==='pointerup'&&!g.moved&&!g.multi){discover((e.clientX-tx)/(W*scale),(e.clientY-ty)/(H*scale));practice('click')}else if(g.moved){practice('drag');if(!reduced.matches&&!g.multi&&performance.now()-g.lastTime<90){let vx=g.vx*14,vy=g.vy*14;function coast(){vx*=.91;vy*=.91;tx+=vx;ty+=vy;paint();if(Math.hypot(vx,vy)>.3)inertia=requestAnimationFrame(coast);else save()}inertia=requestAnimationFrame(coast)}}save()}
viewport.addEventListener('pointerup',endPointer);viewport.addEventListener('pointercancel',endPointer);
viewport.addEventListener('keydown',e=>{if(!started)return;const keys={ArrowLeft:[65,0],ArrowRight:[-65,0],ArrowUp:[0,65],ArrowDown:[0,-65]};if(keys[e.key]){e.preventDefault();stop();tx+=keys[e.key][0];ty+=keys[e.key][1];paint();save()}else if(['+','=','-','Home'].includes(e.key)){e.preventDefault();if(e.key==='Home')fit();else zoom(e.key==='-'?1/1.25:1.25)}});
function enter(resume){started=true;lastTick=performance.now();$('welcome').close();if(resume&&state.view)moveTo(state.view.x,state.view.y,minScale*state.view.zoom,false);else moveTo(.52,.51,minScale*(mobile.matches?3:1.65),false);render();$('onboarding').hidden=resume;$('onboarding').querySelector('span').textContent=mobile.matches?'单指移动 · 双指缩放 · 轻点寻找':'拖动移动 · 滚轮缩放 · 点击寻找';viewport.focus();if(!storage)toast('本次进度仅在当前页面保留');save()}
$('start').onclick=()=>{if(saved){openModal('开始新的探索？','已有一份寻趣手帖','<p>开始新探索会清除本地已有的寻物进度。</p>',[['继续原来的探索',()=>{closeModal();enter(true)}],['开始新的探索',()=>{reset();enter(false)},true]])}else enter(false)};
$('resume').onclick=()=>enter(true);$('resume').hidden=!saved;
function load(){loaded=false;$('retry').hidden=true;$('loadStatus').textContent='正在展开画卷…';painting.onload=()=>{W=painting.naturalWidth;H=painting.naturalHeight;world.style.width=W+'px';world.style.height=H+'px';effects.setAttribute('viewBox',`0 0 ${W} ${H}`);resize();loaded=true;$('start').disabled=false;$('resume').disabled=false;$('loadStatus').textContent='画卷已展开 · 可以入城了';if(debug){for(const t of targets){for(const a of t.hitAreas){if(a.type==='rect')svg('rect',{x:a.x*W,y:a.y*H,width:a.w*W,height:a.h*H,class:'debug'});else svg('polygon',{points:a.points.map(p=>`${p[0]*W},${p[1]*H}`).join(' '),class:'debug'})}svg('text',{x:t.focusPoint[0]*W,y:t.focusPoint[1]*H,class:'debug-label'}).textContent=t.id}toast('开发调试：热点已显示，按 R 重置')}};painting.onerror=()=>{$('loadStatus').textContent='画卷加载失败，请检查网络后重试。';$('retry').hidden=false};painting.src='assets/explore/painting.webp'+(painting.src?'?retry='+Date.now():'')}
$('retry').onclick=load;$('welcome').addEventListener('cancel',e=>e.preventDefault());$('welcome').showModal();load();render();
window.addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{lastTick=performance.now();if(document.hidden)save()});window.addEventListener('pagehide',save);
setInterval(()=>{const now=performance.now();if(started&&!document.hidden&&!$('modal').open&&!$('welcome').open)state.seconds+=(now-lastTick)/1000;lastTick=now},1000);setInterval(save,5000);
if(debug)document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r'&&!$('modal').open)confirmReset()});
